model_params:
  name: 'Hash_Contra_IR'
  img_size: 224
  in_channels: 3
  latent_dim: 64
  learnable_parameter_dim: 64
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000 
  hypermeter: [1, 0, 1, 1, 0.5]
  backbone : COCO_AE
  path :  './logs/test_lantent_z/COCOPretrained.ckpt'

exp_params:
  ckpt_path: './logs/test_lantent_z/COCO.ckpt'
  dataset: mscoco_paired
  data_path: "./coco" 
  img_size: 224
  batch_size: 128 # Better to have a square number 
  LR: 0.0005
  momentum : 0.9
  weight_decay: 0.0
  #scheduler_gamma: 0.95
  num_epochs: 200

trainer_params:
  gpus: 1
  distributed_backend: 'dp'
  num_nodes: 1
  max_nb_epochs: 200
  max_epochs: 200
  epochs: 200

logging_params:
  save_dir: "logs/"
  name: "COCO_64_0_299" 
  manual_seed: 1265
